version: '3'

services:
        db:
                image: postgres
        web:
                build: .
                command: python3 manage.py runserver 0.0.0.0:9000
                volumes:
                        - .:/code
                ports:
                        - "9000:9000"
                depends_on:
                        - migration
        migration:
                build: .
                image: python:3
                command: python3 /code/manage.py makemigrations houses
                command: python3 /code/manage.py migrate
                volumes:
                        - .:/code
                depends_on:
                        - db
